### PR TITLE
support catch without error

### PR DESCRIPTION
**Pull request by LongTengDao**
```js
try { }
catch { }
```

### CODE REVIEW

**Comment by corwin-of-amber** [comment]
I came across this bug as well. Thanks @LongTengDao for the fix. Any chance this can be merged?

**Comment by LongTengDao** [comment]
> cross this bug as well. Thanks @LongTengDao for the fix. Any chance this can be merged?

I think @ForbesLindesay is busy, I'm waiting for his time.

**Comment by pronav** [comment]
Facing the same issue. @ForbesLindesay can you please merge this to enable optional catch binding?

**Comment by corwin-of-amber** [comment]
Or, can you please give @LongTengDao permission to update the NPM package?

**Comment by nicolashenry** [comment]
@ForbesLindesay Can you take a quick peek? :)

**Comment by ForbesLindesay** [comment]
@LongTengDao  Sorry for the (extreme) delay in reviewing this. I'll add you as a contributor so you can review & merge changes in future.

I've set up Rolling Versions now so that contributors on GitHub can release new versions via CI after merging changes. Just click the "Rolling Versions: Enabled" badge in the README to preview & trigger the next release. Where possible, please try to get a second review on any changes you make yourself, but feel free to merge if nobody has responded within a week or so. Please never commit directly to the "master" branch.

**Comment by LongTengDao** [comment]
> @LongTengDao Sorry for the (extreme) delay in reviewing this. I'll add you as a contributor so you can review & merge changes in future.
> 
> I've set up Rolling Versions now so that contributors on GitHub can release new versions via CI after merging changes. Just click the "Rolling Versions: Enabled" badge in the README to preview & trigger the next release. Where possible, please try to get a second review on any changes you make yourself, but feel free to merge if nobody has responded within a week or so. Please never commit directly to the "master" branch.

@ForbesLindesay Thanks for trust. I just saw the invitation message, it has expired, sorry.

**Pull request merged**
