### PR TITLE
Update acorn to 7.1.1

### PR DESCRIPTION
**Pull request by EmmaGoodliffe**
Fixes following error from running `npm audit`:
```
  Moderate        Regular Expression Denial of Service                          

  Package         acorn                                                         

  Patched in      >=7.1.1                                                       

  Dependency of   acorn-globals                                        

  Path            acorn-globals > acorn                               

  More info       https://npmjs.com/advisories/1488  
```

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Bot already opened a PR #50.

**Comment by EmmaGoodliffe** [comment]
Awesome! Thank you!

**Comment by tunnckoCore** [comment]
In anyway, please don't delete your branch since I suggested it as install method in several places :laughing:

**Comment by EmmaGoodliffe** [comment]
So sorry! I didn’t see this message. But thank you for your responsiveness! I really appreciate you taking the time to fix the problem

**Pull request closed without merging**
