### PR TITLE
acorn upgraded to 0.11.0

### PR DESCRIPTION
**Pull request by ppitonak**

### CODE REVIEW

**Comment by shinnn** [comment]
:+1: but current latest version of [acorn](https://github.com/marijnh/acorn) is [0.11.0](https://github.com/marijnh/acorn/releases/tag/0.11.0).

**Comment by ppitonak** [comment]
You're right, a new version of acorn was released after my PR. Do  you want me to prepare a new PR or will you do it yourself?

**Comment by shinnn** [comment]
> prepare a new PR

It's better to *update* this PR. Of course, if you don't have any time to do so, I'll create a new PR.

**Comment by ppitonak** [comment]
I updated the PR.

**Comment by shinnn** [comment]
@ForbesLindesay What do you think?

**Comment by shinnn** [comment]
Thanks for the new release. https://github.com/ForbesLindesay/acorn-globals/commit/68924f70b222871cce16b236bede9bda087e08bb

**Pull request merged**
