### PR TITLE
Use specific acorn vesion 0.12.0

### PR DESCRIPTION
**Pull request by letunglam**
As acorn/util/walk.js has been removed in latest version

### CODE REVIEW

**Comment by ForbesLindesay** [comment]
Which version of npm do you have?  It shouldn't have picked up 1.x.x anyway because the version specifier already excluded that?

**Comment by letunglam** [comment]
My NPM version is 1.3.2

**Comment by ForbesLindesay** [comment]
That'll be why then :)  I'm using 2.5.1, if you update npm then it'll install the correct version of the dependency.

**Comment by letunglam** [comment]
Yes, thank you for quick update. I also updated my npm to latest version :+1:

**Comment by ForbesLindesay** [comment]
:+1:

**Pull request closed without merging**
