### PR TITLE
Upgrade acorn to version 8

### PR DESCRIPTION
**Pull request by realityking**
Also adds Node.js 14 to the test matrix

Main reason is that jsdom now pulls in both acorn 7 and 8. Getting a new release of acorn-globals will allow for deduplication again.

### CODE REVIEW

**Comment by realityking** [comment]
@ForbesLindesay @TimothyGu Could one of you please have a look? 🙏

**Comment by realityking** [comment]
@ForbesLindesay @TimothyGu Sorry to be a pain but it'd be great if one of you could take a look 🙏 

This is currently causing `jsdom`  to come with both `acorn` 7 and 8. That's not a small dependency and it'd be nice to get it deduplicated.

**Comment by pierogitus** [comment]
@ForbesLindesay @TimothyGu This is also needed for es2022 support which has reached stage 4 and is deployed in major browsers.

**Comment by ForbesLindesay** [comment]
@realityking Sorry for the (extreme) delay in reviewing this. I'll add you as a contributor so you can review & merge changes in future.

I've set up Rolling Versions now so that contributors on GitHub can release new versions via CI after merging changes. Just click the "Rolling Versions: Enabled" badge in the README to preview & trigger the next release. Where possible, please try to get a second review on any changes you make yourself, but feel free to merge if nobody has responded within a week or so. Please never commit directly to the "master" branch.

**Comment by realityking** [comment]
Thanks for following up on this! I’ll be careful with my new powers. 😄
 
Not sure how it plays with the automation you’ve got set up but maybe try making master a protected branch?

**Pull request merged**
