### PR TITLE
Support more parts of ES2015

### PR DESCRIPTION
**Pull request by TimothyGu**

### CODE REVIEW

**Comment by TimothyGu** [comment]
Actually wait, this doesn't work with

```js
function a({b} = 0) {
  
}
```

**Comment by TimothyGu** [comment]
Fixed.

**Comment by ForbesLindesay** [comment]
I've added you as a collaborator and owner on npm.  I've also added you as an owner of jade on npm, as I hadn't really registered that you weren't.

**Comment by TimothyGu** [comment]
> I've also added you as an owner of jade on npm, as I hadn't really registered that you weren't.

Thank you, although I would love to have the permission to publish other jade-* components as well :)

**Pull request merged**
